global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "predictive_maintenance_api"
    static_configs:
      - targets: ["localhost:5001"]
    metrics_path: "/metrics"
    scrape_interval: 5s
